### ISSUE TITLE
Interfacing panic button with LPC2148

### ISSUE THREAD

**Issue by mikeshams** [sharmaronak79/Capstone-project-summer2020#4]

**Comment by mikeshams** [comment]
1. Possible issue connecting Panic Button to an LPC 2148 in terms of hardware and software?

**Comment by Amandeepkaur786** [comment]
Software problems:
as it is new to work lpc2148. Then we have to study about registers.Then we make a schematics design and code related with it.Number of time we change the values in a code and perform simulation.The problem was with battery because in schematics we use lpc2138 which work on 3.3 to 3.6. BuT we have battery supply of 7.4 and 3.7 earlier we were thinking to purchase new one of 3.3 .but after use 3.7 on lpc2148.then itwas  start  working.little issue it was ,but solved it.
