### ISSUE TITLE
Interfacing with Cloud services

### ISSUE THREAD

**Issue by mikeshams** [sharmaronak79/Capstone-project-summer2020#9]

**Comment by mikeshams** [comment]
1.	what issues did you or others might face when interfacing the project to the Blynk cloud services?
2.	how to resolve them?

**Comment by shweta3109** [comment]
1.In terms of hardware,when I tried to upload the code (related to ESP32 and Blynk ),I was not able to upload.
  In terms of software there was not any issue as after installing the libraries,it works well.
2. When I researched on Internet related to this hardware issue,I came to know that GPIO 0 and Ground pin of ESP32 need to be shorted during uploading,When I did that ,the issue was resolved.
